### ISSUE TITLE
Custom heading levels

### ISSUE THREAD

**Issue by sw-yx** [LeaVerou/md-block#1]
Hi Lea, thank you for making this project! Its something I constantly rebuild in projects and am excited by a web component approach that I can style in the normal DOM!

with headings, I often struggle with visual distinction of h3's vs h2's. So on my site i have done [something like this](https://www.swyx.io/api-economy/):

![image](https://user-images.githubusercontent.com/6764957/143620653-4c8a7f40-85a0-4670-8094-76b986bd2db5.png)

and it's really helped me with my "heading anxiety". i wonder if that could be incorporated here in a more generic way?

**Comment by LeaVerou** [comment]
It’s an interesting idea, but I don’t think it’s actually good for information architecture. Higher heading levels need to be more prominent somehow (size, weight etc) to establish a clear visual hierarchy, whereas here the only difference is the number of `#` signs, which a) does not establish prominence visually and b) is also somewhat obscure to non-technical folks. But even for those of us who understand what it means, and think it's cute and creative, it still makes it difficult to process a document’s hierarchy. 😕
