### ISSUE TITLE
How to use md-block with a syntax highlighter?

### ISSUE THREAD

**Issue by just-ero** [LeaVerou/md-block#12]
How would one achieve this? I've tried `highlight.js`, which didn't appear to do anything at all.

Here's my attempt;

```html
<!DOCTYPE html>
<html>
<head>
  <script type="module" src="https://md-block.verou.me/md-block.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css" />
</head>

<body>
  <md-block>
    ```cs
    Console.WriteLine("Hello, world!");
    ```
  </md-block>
</body>
</html>
```

**Comment by atisor73** [comment]
I've been doing the same thing; I believe `highlight.js` requires the code to be in a set of `<pre><code>` tags. For some reason I couldn't get this to work in the `md-block`, so I just end the preceding md-block, create a code block, then resume md-block. Not a fantastic workflow, but I love the themes in `highlight.js` too much to forgo them. 

Basically
```
<md-block> starting text </md-block>
<pre><code> code code code </code></pre>
<md-block> ending text </md-block>
```

However, md-block does support inline code, so like this highlights normally: (though I'm stuck with a pink color that I can't over-ride without over-riding highlight.js's code color).
```
<md-block>
The variable `a` is highlighted normally.
</md-block>
```

Another thing, `highlight.js` tries to auto-detect language, but you can also explicitly set it by changing the name after the dash: 
```
<pre><code class="language-python"> </code></pre>
```

**Comment by just-ero** [comment]
Did you post this answer under the wrong discussion? None of what you posted has anything to do with what I asked about.

**Comment by atisor73** [comment]
I don't believe I am mistaken...

You were asking about using highlight.js and md-block together?

My answer is that highlight.js works with <pre><code> tags and I
believe md-block converts code to just <code> tags, so I exit the md-block
and use <pre><code> tags.

If this is too much work or unhelpful or not what you asked, I can remove
my comment.

**Comment by LeaVerou** [comment]
Md-block supports Prism out of the box, if you import it will automatically use it.
For other highlighters, you can listen to the `md-render` event and invoke them then (or import them then).
