### ISSUE TITLE
external md file not loading

### ISSUE THREAD

**Issue by uinguzero** [LeaVerou/md-block#13]
With just a simple md-block from the demo, everything works,

but when i try to load an external md file using

```
  <script type="module" src="https://md-block.verou.me/md-block.js"></script>
<md-block src="output.md">
	`output.md` was *not* found
</md-block>
```

with output.md on the smae level as my htm file it always shows  `output.md` was *not* found
I've also tried 
`./output.md
`
or the full path
`/home/user/tmp/output.md`

**Comment by LeaVerou** [comment]
How are you running the page? What URL from? What's the file structure? Thanks!

**Comment by uinguzero** [comment]
It is just a standalone html page, which i run in brave, but tested in other browsers as well, like firefox.

`<!doctype html>
<html lang="en">
  <head>
    <title></title>
    <style>
div {
  height: 200px;
  width: 50%;
}
</style>
  </head>

  <body>

  <script type="module" src="https://md-block.verou.me/md-block.js"></script>
<md-block src="/output.md">
	`output.md` was *not* found
</md-block>

  </body>
</html>`


If i copy the content of my output.md file inside the block, it works perfectly, but it does not import it like the code above

**Comment by uinguzero** [comment]
@LeaVerou any news? 
I've tried the demo on the website, and there it works, but when i just put the same code in an stand alone htm file that is running locally on my computer, it doesn't work.

**Comment by LeaVerou** [comment]
md-block uses `fetch()` behind the scenes, and I can't remember if that's one of the APIs that don't work under `file://` (the protocol used when you just open an HTML file with a browser). Try using a local server (localhost) and I think it will solve the problem. In general you'll find more and more things don't work under `file://`, it's considered unsafe, so browsers are not running many APIs on that.

**Comment by uinguzero** [comment]
@LeaVerou you are correct.
When running the page through a local webserver it displays the content of a sourced MD file correctly

**Comment by uinguzero** [comment]
When running the page through a local webserver it displays the content of a sourced MD file correctly

**Comment by mi-hol** [comment]
@uinguzero I've encountered the same issue. Edge suggested "Response should include 'x-content-type-options' header."
Would you perhaps have any experience if that would fix this issue?

link provided is: https://webhint.io/docs/user-guide/hints/hint-x-content-type-options/?source=devtools

![image](https://github.com/user-attachments/assets/f9d0392e-230d-4917-a534-4a7fa8596c12)
