### ISSUE TITLE
How can I use a local copy of  marked.min.js

### ISSUE THREAD

**Issue by halloleo** [LeaVerou/md-block#22]
I have a local copy of  `marked.min.js` (and its dependencies `TextRenderer.js`, `Slugger.js`, etc...), plus I load md-block locally as well:

    <script type="module" src="scripts/md-block.js"></script>

How can I now tell md-block to use the local `script/marked.min.js` and not the CDN `https://cdn.jsdelivr.net/npm/marked/src/marked.min.js`?

**Comment by bejucoo** [comment]
Did you try changing the URL in the md-block.js file? On line 10:

```
export const URLs = {
	marked: "https://cdn.jsdelivr.net/npm/marked/src/marked.min.js",
	DOMPurify: "https://cdn.jsdelivr.net/npm/dompurify@2.3.3/dist/purify.es.min.js"
}
```

**Comment by bejucoo** [comment]
Check the [Using different URLs for marked and DOMPurify](https://github.com/leaverou/md-block?tab=readme-ov-file#using-different-urls-for-marked-and-dompurify) section in the README.
