### ISSUE TITLE
markdown table

### ISSUE THREAD

**Issue by xp12047** [LeaVerou/md-block#6]
The markdown table cannot be displayed normally

**Comment by xp12047** [comment]
I put this |---| in the <md-block> and save it as an html file and I can't see the table

**Comment by LeaVerou** [comment]
Do you have some sample code I could look at? `|---|` by itself is not enough to produce a table.

**Comment by xp12047** [comment]
> 

![Screenshot_20211219_064458_com rhmsoft edit](https://user-images.githubusercontent.com/56335408/146657456-35ea26e0-c0a7-471c-9f7a-158bd83cfff2.jpg)
![Screenshot_20211219_064502_com rhmsoft edit](https://user-images.githubusercontent.com/56335408/146657458-e2b7edbd-1835-419b-8bd5-d3de99fcfc13.jpg)


As you can see, its result is not a regular markdown table, and block references have no effect.  I don’t know if there is a problem with my operation. Solve

**Comment by xp12047** [comment]
I really like your tool, thank you

**Comment by xp12047** [comment]
Seek solution

**Comment by LeaVerou** [comment]
Not sure what you mean "the result is not a regular markdown table", it looks like a table to me!
Do note that there's no CSS that ships with `<md-block>`, how you style the HTML generated is up to you. Maybe that's the source of the confusion?

**Comment by xp12047** [comment]
Thanks, I will try again
